--SCRIPT DE LOS COMPONENTES DE BASE DE DATOS
--TABLA PADRE
CREATE TABLE VETERINARIAS(
    ID_VETERINARIA NUMBER,
    NOMBRE NVARCHAR2(50),
    DIRECCION NVARCHAR2(100),
    TELEFONO NUMBER,
    CONSTRAINT PK_VETERINARIAS PRIMARY KEY (ID_VETERINARIA)
);

--TABLA HIJO
CREATE TABLE RESPONSABLES(
    ID_RESPONSABLE NUMBER,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT PK_RESPONSABLES PRIMARY KEY (ID_RESPONSABLE),
    CONSTRAINT FK_RESPONSABLE_VETERINARIA FOREIGN KEY (VETERINARIA_ID) REFERENCES VETERINARIAS(ID_VETERINARIA)
);

/*CREATE SEQUENCE SEQ_RESPONSABLE_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
MINVALUE 1
NOCYCLE; -- PUEDE SER "NOCYCLE O CYCLE"
ALTER SEQUENCE SEQ_RESPONSABLE_ID RESTART;*/

--DELETE FROM RESPONSABLES;
--SELECT * FROM RESPONSABLES;

--TABLA HIJO
CREATE TABLE MASCOTAS(
    ID_MASCOTA NUMBER,
    NOMBRE NVARCHAR2(15),
    RAZA NVARCHAR2(15),
    EDAD NUMBER,
    RAZON_CITA NVARCHAR2(100),
    CLIENTE_ID NUMBER,
    RESPONSABLE_ID NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT PK_MASCOTAS PRIMARY KEY (ID_MASCOTA),
    CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_RESPONSABLE_ID FOREIGN KEY (RESPONSABLE_ID) REFERENCES RESPONSABLES(ID_RESPONSABLE)
);

--SELECT * FROM MASCOTAS;
--TABLA HIJO
CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(50),
    DIRECCION NVARCHAR2(100),
    CONTACTO NUMBER,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);