--SCRIPT DE LOS COMPONENTES DE BASE DE DATOS
--TABLA PADRE
CREATE TABLE VETERINARIAS(
    ID_VETERINARIA NUMBER,
    NOMBRE NVARCHAR2(50),
    DIRECCION NVARCHAR2(100),
    TELEFONO NUMBER,
    CONSTRAINT PK_VETERINARIAS PRIMARY KEY (ID_VETERINARIA)
);

--TABLA HIJO
CREATE TABLE RESPONSABLES(
    ID_RESPONSABLE NUMBER,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT PK_RESPONSABLES PRIMARY KEY (ID_RESPONSABLE)
);

//Secuencia de responsables
CREATE SEQUENCE SEQ_RESPONSABLE_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
MINVALUE 1
NOCYCLE; -- PUEDE SER "NOCYCLE O CYCLE"

//Secuencia de mascotas
CREATE SEQUENCE SEQ_MASCOTA_ID
START WITH 1003
INCREMENT BY 1
MAXVALUE 10000
MINVALUE 1000
NOCYCLE; -- PUEDE SER "NOCYCLE O CYCLE"
//
ALTER SEQUENCE SEQ_RESPONSABLE_ID RESTART;

--DELETE FROM RESPONSABLES;
SELECT * FROM RESPONSABLES;
SELECT * FROM VETERINARIAS;
SELECT * FROM MASCOTAS;

--TABLA HIJO
CREATE TABLE MASCOTAS(
    ID_MASCOTA NUMBER,
    NOMBRE NVARCHAR2(15),
    RAZA NVARCHAR2(15),
    EDAD NUMBER,
    RAZON_CITA NVARCHAR2(100),
    CLIENTE_ID NUMBER,
    RESPONSABLE_ID NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT PK_MASCOTAS PRIMARY KEY (ID_MASCOTA)
);

--SELECT * FROM MASCOTAS;
--TABLA HIJO
CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(50),
    DIRECCION NVARCHAR2(100),
    CONTACTO NUMBER,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);